In [6]:
from sklearn.datasets import load_iris

In [10]:
#Spliting dataset
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3,random_state=1)
print(X_train.shape)
print(X_test.shape)


print(y_train.shape)
print(y_test.shape)
# print(y_train)

(105, 4)
(45, 4)
(105,)
(45,)
[2 0 0 0 1 0 0 2 2 2 2 2 1 2 1 0 2 2 0 0 2 0 2 2 1 1 2 2 0 1 1 2 1 2 1 0 0
 0 2 0 1 2 2 0 0 1 0 2 1 2 2 1 2 2 1 0 1 0 1 1 0 1 0 0 2 2 2 0 0 1 0 2 0 2
 2 0 2 0 1 0 1 1 0 0 1 0 1 1 0 1 1 1 1 2 0 0 2 1 2 1 2 2 1 2 0]


In [7]:
iris = load_iris()
X = iris.data
y= iris.target

feature_names = iris.feature_names

target_names= iris.target_names

print("Feature name:", feature_names)

print("Target names:", target_names)
print("\nFirst 10 rows of X:\n", X[:10])

Feature name: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']

First 10 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [21]:
#K nearest neighbors
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
classifier_knn = KNeighborsClassifier(n_neighbors=3)



classifier_knn.fit(X_train, y_train)

y_pred = classifier_knn.predict(X_test)
# Finding accuracy by comparing actual response values(y_test)with predictedresponse value(y_pred)
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
# Providing sample data and the model will make prediction out of that data
sample = [[5, 5, 3, 2], [2, 4, 3, 5]]
preds = classifier_knn.predict(sample)
pred_species = [iris.target_names[p] for p in preds] 
print("Predictions:",pred_species)

Accuracy: 0.9777777777777777
Predictions: ['versicolor', 'virginica']


In [35]:
import joblib
joblib.dump(classifier_knn, 'iris_classifier_knn.joblib')

['iris_classifier_knn.joblib']

In [36]:
joblib.load('iris_classifier_knn.joblib')

KNeighborsClassifier(n_neighbors=3)

In [41]:
import numpy as np
from sklearn import preprocessing

input_data = np.array([[2.1, -1.9, 5.5],
                       [-1.5, 2.4, 3.5],
                       [0.5, -7.9, 5.6],
                       [5.9, 2.3, -5.8]])

data_binarized = preprocessing.Binarizer(threshold=0.5).transform(input_data)
print("\nBinarized data:\n", data_binarized)



Binarized data:
 [[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [1. 1. 0.]]


In [42]:
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Calculate the mean for each feature
means = np.mean(data, axis=0)

# Subtract the mean from each data point
centered_data = data - means

print("Original Data:\n", data)
print("Mean:\n", means)
print("Centered Data:\n", centered_data)

Original Data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean:
 [4. 5. 6.]
Centered Data:
 [[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]
